# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZemogaPost' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZemogaPost
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'KVNProgress'

  target 'ZemogaPostTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZemogaPostUITests' do
    # Pods for testing
  end

end
